version: '3.7'

services:
    server:
        build: ./server
        command: flask run --host=0.0.0.0
        volumes:
          - ./server/:/usr/src/app/
        ports:
          - 5000:5000
        environment:
            - FLASK_APP=server.py
    client:
        stdin_open: true
        build:
          context: ./client
          dockerfile: Dockerfile
        volumes:
          - './client:/usr/src/app'
        ports:
          - '3001:3000'
        environment:
          - NODE_ENV=development
        links:
          - server
